apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: d-platypus-nmmo-nips
  name: d-platypus-nmmo-nips
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: d-platypus-nmmo-nips
    spec:
      containers:
        - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          name: platypus-nmmo-container