apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: d-platypus-nmmo-nips
  name: d-platypus-nmmo-nips
  namespace: default
spec:
  selector:
    matchLabels:
      app: d-platypus-nmmo-nips
  template:
    metadata:
      labels:
        app: d-platypus-nmmo-nips
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          name: platypus-nmmo-container
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm